version: '3.6'
services:
 web:
  build: .
  image: jerrychen1013/php:5.3.29-fpm
  volumes:
  - ./projects:/var/www/html
  - ./etc/php/php.ini:/usr/local/etc/php/php.ini
  - ./etc/php/conf.d:/usr/local/etc/php/conf.d
  ports:
   - "80:80"
  networks:
    - net

######top-level netowks key#######
networks:
    net: